Manual/Simp.lean
=> fix: minor typo

lake-manifest.json
Adds navigation buttons to the ToC.
=> chore: update Verso for nav buttons

Main.lean, Manual.lean, Manual/BasicTypes.lean, Manual/BasicTypes/Nat.lean, Manual/BasicTypes/String.lean, Manual/BasicTypes/String/FFI.lean, Manual/BasicTypes/String/Literals.lean, Manual/Intro.lean, Manual/Language/Files.lean, Manual/Language/Functions.lean, Manual/Language/InductiveTypes.lean, Manual/Language/InductiveTypes/LogicalModel.lean, Manual/Language/InductiveTypes/Structures.lean, Manual/Simp.lean, Manual/Tactics.lean, Manual/Tactics/Conv.lean, Manual/Tactics/Custom.lean, Manual/Tactics/Reference.lean, Manual/Tactics/Reference/Simp.lean, Manual/Terms.lean, lake-manifest.json
Bump Verso to get repo links and permalink widgets; also add tags to every section to get stable link targets.
=> chore: permalinks and repo links

lake-manifest.json
=> chore: bump Verso to fix index

Manual.lean, Manual/BasicTypes.lean
=> feat: Unit type

.github/workflows/ci.yml, CONTRIBUTING.md
This is also a test to see if the new CI setup from #202 works.
=> doc: Add PR deployment info to CONTRIBUTING.md

.vale/styles/config/ignore/terms.txt, Manual/Language.lean, Manual/NotationsMacros/SyntaxDef.lean
=> feat: describe section scopes

Manual/Language/Files.lean
=> feat: improve description of comments

Manual/Terms.lean
=> feat: improve description of instance implicits

Manual.lean, Manual/BasicTypes.lean, Manual/BasicTypes/Fin.lean, Manual/BasicTypes/Nat.lean, Manual/Meta/Lean.lean
=> feat: Fin chapter

Manual/BasicTypes.lean, Manual/BasicTypes/Int.lean, Manual/BasicTypes/Nat.lean, Manual/Classes/BasicClasses.lean, Manual/Tactics.lean, Manual/Terms.lean
=> feat: Ints and Nat representation

Manual.lean, Manual/BasicTypes.lean, Manual/BasicTypes/Empty.lean
=> feat: document Empty

.github/workflows/pr-deploy.yml
instead of reacting on label changes. This copies the setup found in
https://github.com/leanprover/reference-manual/blob/main/.github/workflows/pr-deploy.yml
=> chore: Use on workflow_run

Manual/BuildTools/Lake/Config.lean
=> fix: `scope` is required for Reservoir require

.github/workflows/ci.yml, .vale/styles/Lean/Names.yml, .vale/styles/Lean/TechnicalTerms.yml, .vale/styles/config/ignore/names.txt, .vale/styles/config/ignore/terms.txt, CONTRIBUTING.md, Manual/BasicTypes/Int.lean, Manual/BasicTypes/Nat.lean, Manual/Coercions.lean, Manual/Language.lean, Manual/Meta/Attribute.lean, Manual/Monads/Lift.lean, Manual/NotationsMacros/SyntaxDef.lean, Manual/Types.lean, README.md, figures/coe-chain.tex, lakefile.lean
=> feat: coercions

Manual/BasicTypes.lean, Manual/BasicTypes/Products.lean, Manual/Meta/Lean.lean, lake-manifest.json, static/theme.css
=> feat: products

Manual/BasicTypes/String.lean, Manual/Classes/BasicClasses.lean, Manual/Monads/Syntax.lean, lake-manifest.json, lean-toolchain
This gets the latest nightly, plus closes #228.
=> chore: bump Lean and Verso

Manual/BasicTypes.lean, Manual/BasicTypes/List.lean, Manual/BasicTypes/Subtype.lean, Manual/Elaboration.lean, Manual/Language/Functions.lean, Manual/Meta/Lean.lean, Manual/Types.lean, lake-manifest.json
=> feat: Subtype

CONTRIBUTING.md, Manual.lean, Manual/BasicTypes.lean, Manual/BasicTypes/Float.lean, Manual/Terms.lean, lake-manifest.json
=> feat: Float

Manual.lean, Manual/BasicTypes.lean, Manual/BasicTypes/Thunk.lean, figures/thunk.tex, lake-manifest.json
=> feat: Thunk

Manual/BasicTypes/Fin.lean, Manual/BasicTypes/Sum.lean, Manual/Classes.lean, Manual/Classes/BasicClasses.lean, Manual/Classes/InstanceDecls.lean, Manual/Classes/InstanceSynth.lean, Manual/Coercions.lean, Manual/Interaction.lean, Manual/Monads/Lift.lean, Manual/Monads/Zoo.lean, Manual/NotationsMacros/Operators.lean, Manual/Terms.lean, lake-manifest.json, lean-toolchain
2025-02-27 is presently not building, but this should unstick merging the look and feel improvements in #320.
=> chore: bump to nightly-2025-02-26

Manual/Elaboration.lean, Manual/RecursiveDefs/PartialFixpoint.lean, Manual/RecursiveDefs/Structural.lean, Manual/Terms.lean, Manual/Types.lean, lakefile.lean, lean-toolchain
Includes a workaround for https://github.com/leanprover/lean4/issues/7388
=> chore: bump to 2025-03-07

Manual.lean, Manual/Intro.lean, Manual/Meta.lean, lake-manifest.json
This prepares for the imminent snapshot.
=> chore: prepare release snapshot

Manual.lean, Manual/BasicTypes.lean, Manual/BasicTypes/Fin.lean, Manual/BasicTypes/List.lean, Manual/BasicTypes/Option.lean, Manual/BasicTypes/Products.lean, Manual/BasicTypes/Sum.lean, Manual/Classes/BasicClasses.lean, Manual/Coercions.lean, Manual/Language/Functions.lean, Manual/Meta/Lean/Scopes.lean, Manual/Monads/Laws.lean, Manual/Quotients.lean, lake-manifest.json, static/theme.css
This is the corresponding PR for https://github.com/leanprover/lean4/pull/7365 and should be coordinated with it.
=> chore: synchronize with upstream docstring content updates

Manual.lean, Manual/IO.lean, Manual/IO/Files.lean, Manual/Monads/Zoo.lean
Fixes issues found with the IO sections while reviewing docstrings.
=> fix: IO docstring fixes

Manual/BuildTools/Lake/Config.lean, Manual/Classes.lean, Manual/Classes/InstanceDecls.lean, Manual/Elaboration.lean, Manual/Interaction.lean, Manual/Language.lean, Manual/Language/Files.lean, Manual/Language/InductiveTypes.lean, Manual/Language/InductiveTypes/Structures.lean, Manual/Meta/Syntax.lean, Manual/Monads/Zoo/State.lean, Manual/NotationsMacros.lean, Manual/NotationsMacros/Notations.lean, Manual/NotationsMacros/Operators.lean, Manual/NotationsMacros/Precedence.lean, Manual/Simp.lean, Manual/Tactics.lean, Manual/Tactics/Conv.lean, Manual/Terms.lean, Manual/Types.lean, lake-manifest.json
This means they can't be forgotten or overlooked.
=> feat: mandatory titles for syntax blocks

Manual/NotationsMacros.lean, Manual/NotationsMacros/Elab.lean
=> feat: elaborator overview

Manual/Quotients.lean, Manual/Types.lean
Also adds quotient reduction to the list of reduction types.
Fixes #343
=> fix: clarify defeq

.vale/styles/config/ignore/terms.txt, Manual.lean, Manual/Elaboration.lean, Manual/IO/Threads.lean, Manual/Meta/Lean.lean, Manual/Papers.lean, Manual/Runtime.lean
Addresses the highest-priority parts of #208. Guidance on the C FFI is not yet written.
=> feat: reference counting

.vale/styles/config/ignore/terms.txt, Manual/Language.lean, Manual/Language/InductiveTypes.lean, Manual/Meta/Syntax.lean, Manual/Types.lean
=> feat: signatures, auto-implicits, and attributes

.github/workflows/ci.yml, Manual.lean, Manual/BuildTools.lean, Manual/BuildTools/Elan.lean, Manual/Meta/ElanCheck.lean, Manual/Meta/ElanCmd.lean, Manual/Meta/ElanOpt.lean, Manual/Meta/ExpectString.lean, static/search/domain-mappers.js, static/search/search-box.css
=> feat: elan chapter

Manual/Language/InductiveTypes.lean, Manual/Language/InductiveTypes/LogicalModel.lean, Manual/Language/InductiveTypes/Nested.lean
=> feat: nested inductives

.vale/styles/Lean/TechnicalTerms.yml, Manual/Classes/InstanceSynth.lean, Manual/Meta/Syntax.lean, Manual/RecursiveDefs.lean, Manual/Simp.lean, Manual/Tactics/Reference.lean
=> feat: reducibility

Manual/Language.lean, Manual/Language/Files.lean, Manual/Language/Namespaces.lean, Manual/Terms.lean
This is a very rough draft that needs revision.
Closes #210.
=> feat: namespaces

Manual/Elaboration.lean, Manual/RecursiveDefs.lean, Manual/RecursiveDefs/Structural.lean
=> feat: partial and unsafe definitions

Manual/Language/InductiveTypes.lean, Manual/Language/InductiveTypes/LogicalModel.lean
=> fix: wrong constructor parameter type in example

.gitignore, ExtractExplanationExamples.lean, lakefile.lean
This PR adds a preprocessor for elaborating error explanation code blocks in batches based on their import sets.
=> feat: add error explanation preprocessor

Manual/Language/InductiveTypes/Nested.lean
Addresses most of #409, though a precise definition of strict positivity for nested inductives would still be good to have.
=> fix: add missing requirements for nested inductive definitions

Manual/BasicTypes.lean, Manual/BuildTools/Lake/Config.lean, Manual/Coercions.lean, Manual/Elaboration.lean, Manual/Interaction/FormatRepr.lean, Manual/Language/InductiveTypes/Structures.lean, Manual/Language/Namespaces.lean, Manual/Meta.lean, Manual/Meta/CheckMessages.lean, Manual/Monads/Syntax.lean, Manual/Monads/Zoo/Combined.lean, Manual/Monads/Zoo/Except.lean, Manual/Monads/Zoo/State.lean, Manual/Namespaces.lean, Manual/NotationsMacros.lean, Manual/NotationsMacros/Notations.lean, Manual/NotationsMacros/Operators.lean, Manual/NotationsMacros/SyntaxDef.lean, Manual/Quotients.lean, Manual/RecursiveDefs/Structural/CourseOfValuesExample.lean, Manual/RecursiveDefs/WF.lean, Manual/Simp.lean, Manual/SourceFiles.lean, Manual/Terms.lean, Manual/Types.lean
This should fail less frequently when updating the nightly-testing branch.
=> feat: less-fragile #guard_msgs for internal tests

Manual/Simp.lean
=> fix: grammatical error

Manual/Grind.lean
This PR adds some further `grind` examples enabled by `nightly-2025-06-29`. This will need to wait for merging until `nightly-testing` is on a compatible toolchain.
=> feat: further `grind` examples

Manual/Papers.lean
=> fix: McBrid, -> McBride
