leanprover/reference-manual

Manual/Language.lean
Manual/Meta/Syntax.lean

fix: use the correct `example` command

---

.github/workflows/ci.yml

Right now it's a blocker, we can re-enable later.

chore: disable offline link checker for release mode

---

.github/workflows/ci.yml
.vale/scripts/report.py

`vale-action` isn't really designed for checking generated code. This should be more readable in PR reports.

chore: more readable lint reports

---

Manual/Language.lean
Manual/Language/Functions.lean

Fixes an incorrect word and a dodgy example that relied on https://github.com/leanprover/lean4/issues/6117

fix: fixes from Zulip

---

.vale/styles/Lean/Names.yml
.vale/styles/config/ignore/names.txt
Manual.lean
Manual/BasicTypes.lean
Manual/Language/Classes/BasicClasses.lean

feat: Bool

---

Manual/Language/Files.lean

fix: clarify lexical syntax of identifiers

---

lake-manifest.json

This adds JS that adds trailing slashes to work around a hosting issue. This will let us disable the redirects on the server side that aren't being proxied correctly, at least as a temporary solution.
RE #224

fix: bump Verso dep

---

Manual/Simp.lean

This change adds a missing word and corrects one minor typographic error.

fix: minor typo/typography in Simp.lean

---

Manual.lean
Manual/BasicTypes.lean
Manual/BasicTypes/Option.lean

feat: Option

---

Manual/Language.lean

I'd like a tag on this section so that I can link to it.

chore: add tag to header "Section Variables"

---

Manual/RecursiveDefs/WF.lean

Just a redundant "recursion". Although the fact that the term "induction-recursion" exists makes me wonder if this isn't actually a typo :)

fix: remove a typo in WF.lean

---

Manual/BasicTypes/UInt.lean

fix: correct the description of integer representation

---

Manual/Quotients.lean
Manual/Tactics/Reference.lean
lake-manifest.json

This gets access to the page-local ToC items in the upstream library, including sub*sections.
Closes #236

chore: bump Verso

---

static/theme.css

This has annoyed me for a while. It seems something has changed in the rendering of the contents on the chapter-pages, so they don't show the sub-lists anymore. But the index still does. This changes the index from looking like this:
To looking like this:

fix: make distance between list element title and sublist the same

---

static/search/search-box.css
static/theme.css

It will now slide over the title, instead of sliding off the screen.
This is built on top of, but can be merged without https://github.com/leanprover/verso/pull/315.
Closes #318 .

fix: fallback for the quick jump when the title is too long for small screens

---

Manual/BasicTypes/BitVec.lean
Manual/BasicTypes/Products.lean
Manual/BasicTypes/String/Literals.lean
Manual/Intro.lean
Manual/Meta/Basic.lean
Manual/Meta/Lean.lean
Manual/NotationsMacros.lean
Manual/NotationsMacros/Notations.lean
Manual/NotationsMacros/Operators.lean
Manual/NotationsMacros/SyntaxDef.lean
lake-manifest.json

Before, the parser's stopping position was indicated, but this was confusing. Now, the same heuristic as the language server is used to assign a range to the syntax error display, and it looks like other rendered errors.

fix: synchronize display of syntax errors with Lean language server

---

static/search/search-box.css

I'd like a second opinion before we merge this. I think it's better than what we have currently for mobile, but I think @ashandoak should take a look too.

fix: couple the term and domain in the quick jump bar tighter on mobile

---

Manual/Meta/Marginalia.lean

Otherwise they go over the edge of the page.
Requires https://github.com/leanprover/verso/pull/326 before it makes sense.

feat: limit footnote width when content is centered on a large screen

---

Manual/BasicTypes/Nat.lean

The docstring for `Nat` was very long, but had good information. Now it's moved here, in preparation for merging the PR that simplifies the docstring.
Closes #365

feat: ensure that `Nat` docstring information ends up here

---

.vale/styles/config/ignore/terms.txt
Manual/Meta/Example.lean
Manual/Meta/Lean/IO.lean
Manual/Meta/Marginalia.lean
Manual/Meta/Syntax.lean
static/theme.css

fix: display the label consistently over namedocs headers
fix: overflowing code examples, IO
fix: centralize warning color
fix: make example header fully clickable
Examples were only clickable on the line of the text. Now the whole
header is clickable.
fix: increase side margin for marginalia on medium screens

fix: several small UI fixes

---

Manual/Releases/v4.19.0.lean

This PR adds highlights to v4.19 release notes and reorganizes entries in the extended list.

chore: add highlights for v4.19 release notes

---

Manual/Meta/ExpectString.lean
Manual/Meta/LakeToml.lean

Example issue:
```
✖ [469/477] Building Manual.BuildTools.Elan
error: reference-manual/Manual/BuildTools/Elan.lean:226:0: Mismatched 'elan --help' output output:
^^^^^^^^^^^^^
```
`main` branch:
```
Manual/Meta/ExpectString.lean:    logErrorAt expected m!"Mismatched {what} output:\n{Diff.linesToString diff}"
…
Manual/Meta/ElanCheck.lean:    discard <| expectString "'elan --help' output" str elanOutput (useLine := useLine) (preEq := String.trimRight)
Manual/Meta/ExpectString.lean:def expectString (what : String) (expected : StrLit) (actual : String)
Manual/Meta/LakeCheck.lean:    discard <| expectString "'lake --help' output" str lakeOutput (useLine := useLine)
Manual/Meta/LakeToml.lean:        discard <| expectString "elaborated configuration" expectedStr v (useLine := (·.any …
```

chore: avoid repeated "Mismatched <foo> output output" in `expectString` error message

---

Manual/Defs.lean

The name of the `add` definition suggests that it can be used to calculate the sum of two natural numbers, but in the current form, it is always evaluated to the parameter `n` instead of `n+m`

fix: parameter scope example

---

Manual/Meta/Example.lean

This PR adds a field to the `example` block configuration allowing an example to be open by default. This feature is useful for error explanations, where we would like for this to be the case.

feat: allow examples to be open by default

---

Manual/Coercions.lean

Now that leanprover/lean4#8944 is fixed, no need for the workaround

fix: restore test/example after bug fix in compiler

---

.vale/scripts/rewrite_html.py
Manual.lean
Manual/ErrorExplanations.lean
Manual/Meta/ErrorExplanation.lean
static/search/domain-mappers.js
static/search/search-box.css

This PR adds elaboration and a manual page for error explanations.

feat: add error explanation elaboration and manual page

---

Manual/BasicTypes/Fin.lean
Manual/BasicTypes/Sum.lean
Manual/BuildTools/Lake/Config.lean
Manual/Classes.lean
Manual/Classes/BasicClasses.lean
Manual/Classes/InstanceDecls.lean
Manual/Classes/InstanceSynth.lean
Manual/Coercions.lean
Manual/Defs.lean
Manual/ErrorExplanations.lean
Manual/Interaction.lean
Manual/Language/InductiveTypes.lean
Manual/Meta/ErrorExplanation.lean
Manual/Meta/LakeToml.lean
Manual/Monads/Lift.lean
Manual/Monads/Zoo.lean
Manual/Namespaces.lean
Manual/NotationsMacros/Elab.lean
Manual/NotationsMacros/Operators.lean
Manual/RecursiveDefs.lean
Manual/SourceFiles.lean
Manual/Terms.lean
lean-toolchain

Bump to latest nightly.
Adds an option to convert error explanation failures into warnings so we can get a build for other CI. This should not be used for releases, only to temporarily allow nightly builds while we wait for fixes upstream.

chore: bump to nightly-2025-06-29

---

Manual/Language/InductiveTypes/LogicalModel.lean

fix: more consistent terminology for inductive types

---

.github/workflows/ci.yml
.github/workflows/merge-main-nightly.yml
.github/workflows/pr-testing.yml
.github/workflows/release-tag.yml
.github/workflows/update-nightly.yml

teatimeguest/setup-texlive-action (and the entire associated GH account) is now 404ing, so we need to use an alternative.

fix: replace use of deleted GH action

---

Manual/Grind.lean

I am not exactly sure what sentence was meant here, but this correction makes grammatical sense and seems to correctly describe the behavior of `grind`.

chore(Grind): fix typo

---

static/print.css

The nav bar took up a lot of space even though it wasn't displayed. I also got rid of the header while I was there.
Some code snippets were printed with a scroll bar instead of wrapping them. Also, footnotes can't float in print note and just looked broken, so I redesigned them as in-line info boxes. They still look a little wonky, but they're a lot better than overlapping digits onto text.
These changes are the result of my experiments on zulip: [#new members > Printable form of language reference? @ 💬](https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/Printable.20form.20of.20language.20reference.3F/near/527227988)
They should help with #434 if one uses a browser to convert the single-page manual to a PDF.

fix: make printed page look somewhat decent

---

lakefile.lean

LLVM is spending tons of time in the Localizer pass. These flags disable it, and the overall build-and-execute time on one machine went from 237s to 185s.

chore: better LLVM flags

---

Manual/BuildTools/Lake/Config.lean
Manual/Meta/LakeToml.lean

Auto-generation didn't pick this up correctly.

fix: add missing name fields to Lake TOML config section

---

Manual/BasicTypes/Array/Subarray.lean

This PR reintroduces the references to some `Subarray`-related functions that have been temporarily removed in a96c958 in order to fix the reference manual build. In the meantime, the underlying problems have been resolved in https://github.com/leanprover/lean4/pull/9234.

feat: reintroduce `Subarray`-related references

---

Manual/Releases/v4_23_0.lean

This PR adds highlights section to Lean v4.23 release notes.

chore: add highlights for v4.23.0 release notes

---

Main.lean

This PR removes Scarf analytics (which we have decided not to adopt) and updates the Plausible analytics script to conform with the lean-lang.org Plausible script.

chore: update web analytics

---

Main.lean

This is a no-op change for the current verso, but its necessary for the reference manual to continue working when leanprover/verso#530 gets merged, because that PR moves `extraJs` and `extraCss` to including inline js/css (making it parallel to other configuration objects in verso) and requires static js and css assets to be included, for now at least, via extraHead configuration.

chore: use extraHead to include static CSS and JS in the manual
